# Generated by Django 5.2.13 on 2026-05-28 14:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_oficio_rol_ubicacion_usuario_delete_profesional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oficio',
            name='nombre_oficio',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='rol',
            name='nombre_rol',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='dni',
            field=models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\d{7,8}$')]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='oficio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.oficio'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.rol'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='ubicacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.ubicacion'),
        ),
    ]
